spring:
  application:
    name: inventario

  datasource:
    url: jdbc:mysql://localhost:3306/inventario?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Monaco17n.

  jpa:
    hibernate:
      ddl-auto: update     # crea/actualiza las tablas
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

server:
  port: 8080

